services:

  static_hosting:
    image: nginx:latest
    container_name: static_hosting
    volumes:
      - ./moz-todo-react/dist:/usr/share/nginx/html:ro
      - ./settings/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"