name: test_consultation
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download sources
      uses: actions/checkout@v5

    - name: Set up NodeJS
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
        cache-dependency-path: moz-todo-react/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd moz-todo-react
        npm install
    - name: Generate sample
      run: |
        mkdir moz-todo-react/public
        npx --yes dummy-json sample_data.hbs > moz-todo-react/public/sample_data.json 
    - name: Build frontend
      run: |
        cd moz-todo-react
        npm run build
    - name: Start frontend
      run: |
        docker compose up --detach
    - name: Install GreenIT analysis CLI
      run: |
          wget https://github.com/cnumr/GreenIT-Analysis-cli/archive/refs/heads/master.zip
          unzip master.zip
          cd GreenIT-Analysis-cli-master
          npm install
          npm link
    - name: Wait for frontend
      uses: docker://benel/wait-for-response:1
      with:
        args: http://localhost/ 200 30000 500
    - name: Run GreenIT Analysis CLI
      run: |
        greenit analyse --format html --ci scenarios/consult_edt.yml
    - name: Save results
      uses: actions/upload-artifact@v4
      with:
        name: EcoIndex
        path: Consulterl'emploidutemps.html